// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Messenger is the service bound to the frontend. The same code runs in the
 * desktop app and in server (web) mode.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Backup uploads messages not yet in the history backup now.
 */
export function Backup(): $CancellablePromise<number> {
    return $Call.ByID(758421255);
}

export function Chats(): $CancellablePromise<$models.Chat[] | null> {
    return $Call.ByID(3197888096);
}

export function CreateChat(name: string, usernames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3275383003, name, usernames);
}

export function Devices(): $CancellablePromise<$models.Device[] | null> {
    return $Call.ByID(1826830584);
}

/**
 * DownloadFile returns a received file (decrypted) as base64.
 */
export function DownloadFile(chatID: string, seq: number): $CancellablePromise<$models.FileData | null> {
    return $Call.ByID(268098135, chatID, seq);
}

/**
 * GetState returns what the UI needs on start.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(3948464848);
}

export function Invite(chatID: string, usernames: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1649811096, chatID, usernames);
}

export function Keys(username: string): $CancellablePromise<$models.DeviceKey[] | null> {
    return $Call.ByID(3504242277, username);
}

/**
 * Login adds this app as a new device of an existing account.
 */
export function Login(server: string, username: string, password: string, deviceName: string, seedPhrase: string): $CancellablePromise<$models.LoginResult | null> {
    return $Call.ByID(1734906618, server, username, password, deviceName, seedPhrase);
}

export function Members(chatID: string): $CancellablePromise<$models.Member[] | null> {
    return $Call.ByID(1310962584, chatID);
}

export function Messages(chatID: string, limit: number): $CancellablePromise<$models.Message[] | null> {
    return $Call.ByID(2792303965, chatID, limit);
}

export function MyFingerprint(): $CancellablePromise<string> {
    return $Call.ByID(3488752829);
}

/**
 * Register creates an account and returns the seed phrase (shown once).
 */
export function Register(server: string, username: string, password: string, deviceName: string): $CancellablePromise<string> {
    return $Call.ByID(2407790920, server, username, password, deviceName);
}

/**
 * Relogin renews the session of this device after it expired.
 */
export function Relogin(password: string): $CancellablePromise<void> {
    return $Call.ByID(3836286789, password);
}

export function Remove(chatID: string, username: string): $CancellablePromise<void> {
    return $Call.ByID(4231631669, chatID, username);
}

export function RevokeDevice(deviceID: string): $CancellablePromise<number> {
    return $Call.ByID(2532478977, deviceID);
}

export function Send(chatID: string, text: string): $CancellablePromise<$models.Message | null> {
    return $Call.ByID(1304675479, chatID, text);
}

/**
 * SendFile sends a file given as base64.
 */
export function SendFile(chatID: string, name: string, dataBase64: string): $CancellablePromise<$models.Message | null> {
    return $Call.ByID(1589692329, chatID, name, dataBase64);
}

/**
 * Sync fetches pending messages and joins the account's groups.
 */
export function Sync(): $CancellablePromise<void> {
    return $Call.ByID(4103508370);
}

export function Trust(username: string, deviceID: string): $CancellablePromise<number> {
    return $Call.ByID(3758595485, username, deviceID);
}
