// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account is the logged-in identity of this device.
 */
export interface Account {
    "username": string;
    "userId": string;
    "deviceId": string;
}

export interface Chat {
    "id": string;
    "name": string;
    "active": boolean;
    "last"?: Message | null;

    /**
     * unix ms
     */
    "updatedAt": number;
}

export interface Device {
    "id": string;
    "name": string;
    "createdAt": number;
    "revoked": boolean;
    "thisDevice": boolean;
}

export interface DeviceKey {
    "deviceId": string;
    "fingerprint": string;
    "status": string;
    "conflictFingerprint"?: string;
    "thisDevice": boolean;
}

export interface FileData {
    "name": string;
    "mime": string;
    "base64": string;
}

export interface FileInfo {
    "name": string;
    "size": number;
}

export interface LoginResult {
    "restored": number;
    "joined": number;
    "requested": number;
}

export interface Member {
    "username": string;
    "userId": string;
    "deviceId": string;

    /**
     * "verified", "seen", "conflict" or "self"
     */
    "status": string;
}

export interface Message {
    "seq": number;
    "id": string;
    "chatId": string;
    "senderId": string;
    "sender": string;

    /**
     * "text" or "file"
     */
    "kind": string;
    "text": string;
    "file"?: FileInfo | null;

    /**
     * unix ms
     */
    "sentAt": number;
    "outgoing": boolean;

    /**
     * Origin: "" direct, "backup" restored, "shared" re-sent by another member.
     */
    "origin": string;
}

/**
 * State describes what the UI should show on start.
 */
export interface State {
    "serverUrl": string;
    "account": Account | null;
    "online": boolean;
    "webMode": boolean;
}

/**
 * UIEvent is pushed to the frontend for everything that happens in the
 * background (new messages, joins, security warnings, connection state).
 */
export interface UIEvent {
    "type": string;
    "chatId"?: string;
    "message"?: Message | null;
    "detail"?: string;
    "count"?: number;
}
